import type { Card } from './types';

export const POKEMON_MOCK_CARDS: Card[] = [
  {
    id: 'pkm-001',
    name: 'Pikachu',
    type: 'pokemon',
    subtype: 'Basic',
    hp: 60,
    energyTypes: ['lightning'],
    rarity: 'Common',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-002',
    name: 'Raichu',
    type: 'pokemon',
    subtype: 'Stage 1',
    hp: 110,
    energyTypes: ['lightning'],
    rarity: 'Uncommon',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-003',
    name: 'Charmander',
    type: 'pokemon',
    subtype: 'Basic',
    hp: 60,
    energyTypes: ['fire'],
    rarity: 'Common',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-004',
    name: 'Charmeleon',
    type: 'pokemon',
    subtype: 'Stage 1',
    hp: 90,
    energyTypes: ['fire'],
    rarity: 'Uncommon',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-005',
    name: 'Charizard ex',
    type: 'pokemon',
    subtype: 'Stage 2',
    hp: 330,
    energyTypes: ['fire'],
    rarity: 'Double Rare',
    expansion: 'Obsidian Flames',
  },
  {
    id: 'pkm-006',
    name: 'Squirtle',
    type: 'pokemon',
    subtype: 'Basic',
    hp: 60,
    energyTypes: ['water'],
    rarity: 'Common',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-007',
    name: 'Wartortle',
    type: 'pokemon',
    subtype: 'Stage 1',
    hp: 90,
    energyTypes: ['water'],
    rarity: 'Uncommon',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-008',
    name: 'Blastoise ex',
    type: 'pokemon',
    subtype: 'Stage 2',
    hp: 330,
    energyTypes: ['water'],
    rarity: 'Double Rare',
    expansion: '151',
  },
  {
    id: 'pkm-009',
    name: 'Bulbasaur',
    type: 'pokemon',
    subtype: 'Basic',
    hp: 70,
    energyTypes: ['grass'],
    rarity: 'Common',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-010',
    name: 'Ivysaur',
    type: 'pokemon',
    subtype: 'Stage 1',
    hp: 100,
    energyTypes: ['grass'],
    rarity: 'Uncommon',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-011',
    name: 'Venusaur ex',
    type: 'pokemon',
    subtype: 'Stage 2',
    hp: 340,
    energyTypes: ['grass'],
    rarity: 'Double Rare',
    expansion: '151',
  },
  {
    id: 'pkm-012',
    name: 'Mewtwo',
    type: 'pokemon',
    subtype: 'Basic',
    hp: 130,
    energyTypes: ['psychic'],
    rarity: 'Rare',
    expansion: '151',
  },
  {
    id: 'pkm-013',
    name: 'Mew ex',
    type: 'pokemon',
    subtype: 'Basic',
    hp: 130,
    energyTypes: ['psychic'],
    rarity: 'Double Rare',
    expansion: '151',
  },
  {
    id: 'pkm-014',
    name: 'Lucario',
    type: 'pokemon',
    subtype: 'Stage 1',
    hp: 120,
    energyTypes: ['fighting'],
    rarity: 'Rare',
    expansion: 'Obsidian Flames',
  },
  {
    id: 'pkm-015',
    name: 'Gengar',
    type: 'pokemon',
    subtype: 'Stage 2',
    hp: 130,
    energyTypes: ['psychic'],
    rarity: 'Rare',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-016',
    name: 'Professor Sycamore',
    type: 'trainer',
    subtype: 'Supporter',
    rarity: 'Uncommon',
    expansion: 'XY',
  },
  {
    id: 'pkm-017',
    name: 'Rare Candy',
    type: 'trainer',
    subtype: 'Item',
    rarity: 'Uncommon',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-018',
    name: 'Ultra Ball',
    type: 'trainer',
    subtype: 'Item',
    rarity: 'Uncommon',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-019',
    name: 'Boss\'s Orders',
    type: 'trainer',
    subtype: 'Supporter',
    rarity: 'Rare',
    expansion: 'Paldea Evolved',
  },
  {
    id: 'pkm-020',
    name: 'Iono',
    type: 'trainer',
    subtype: 'Supporter',
    rarity: 'Rare',
    expansion: 'Paldea Evolved',
  },
  {
    id: 'pkm-021',
    name: 'Lightning Energy',
    type: 'energy',
    subtype: 'Basic',
    energyTypes: ['lightning'],
    rarity: 'Common',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-022',
    name: 'Fire Energy',
    type: 'energy',
    subtype: 'Basic',
    energyTypes: ['fire'],
    rarity: 'Common',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-023',
    name: 'Water Energy',
    type: 'energy',
    subtype: 'Basic',
    energyTypes: ['water'],
    rarity: 'Common',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-024',
    name: 'Grass Energy',
    type: 'energy',
    subtype: 'Basic',
    energyTypes: ['grass'],
    rarity: 'Common',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-025',
    name: 'Psychic Energy',
    type: 'energy',
    subtype: 'Basic',
    energyTypes: ['psychic'],
    rarity: 'Common',
    expansion: 'Scarlet & Violet',
  },
  {
    id: 'pkm-026',
    name: 'Fighting Energy',
    type: 'energy',
    subtype: 'Basic',
    energyTypes: ['fighting'],
    rarity: 'Common',
    expansion: 'Scarlet & Violet',
  },
];

export function getMockCards(game: string): Card[] {
  if (game === 'pokemon') return POKEMON_MOCK_CARDS;
  // For other games, we can return the same mock cards or an empty array
  return POKEMON_MOCK_CARDS.map(c => ({ ...c, id: `${game}-${c.id}` }));
}
